events {}

http {
    include       /etc/nginx/mime.types;

    log_format upstreamlog '$remote_addr - $host [$time_local] '
                           '"$request" $status '
                           'upstream: $upstream_addr '
                           'response_time: $upstream_response_time';

    access_log /var/log/nginx/access.log upstreamlog;

    # RATE LIMIT
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    include /etc/nginx/conf.d/*.conf;
}